/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package br.com.hbobenicio.javaexamples.readfilesanyencoding;

import org.junit.Test;
import static org.junit.Assert.*;

public class MainTest {
    @Test public void testFake() {
        assertNull(null);
    }
}
